install.packages("ggplot2", dependencies = TRUE)
install.packages("dplyr", dependencies = TRUE)
install.packages("shinythemes", dependencies = TRUE)
install.packages("flexdashboard", dependencies = TRUE)
install.packages("fastDummies", dependencies = TRUE)
install.packages("lubridate", dependencies = TRUE)
install.packages("DT", dependencies = TRUE)
